// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Rating struct {
	UserID  int64
	ShowID  string
	Rating  string
	RatedAt time.Time
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
}

type Show struct {
	ID         string
	TmdbID     sql.NullInt64
	Title      string
	Year       string
	PosterPath sql.NullString
	Genre      sql.NullString
	Synopsis   sql.NullString
	Popularity sql.NullFloat64
	CachedAt   time.Time
}

type User struct {
	ID        int64
	GoogleSub string
	Email     string
	Name      string
	AvatarUrl sql.NullString
	CreatedAt time.Time
}

type Verdict struct {
	UserID    int64
	Verdict   string
	Headline  string
	ShowID    sql.NullString
	CreatedAt time.Time
}
