// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countRatings = `-- name: CountRatings :one
SELECT
  SUM(CASE WHEN rating='liked' THEN 1 ELSE 0 END) AS liked,
  SUM(CASE WHEN rating='disliked' THEN 1 ELSE 0 END) AS disliked,
  COUNT(*) AS total
FROM ratings WHERE user_id = ?
`

type CountRatingsRow struct {
	Liked    sql.NullFloat64
	Disliked sql.NullFloat64
	Total    int64
}

func (q *Queries) CountRatings(ctx context.Context, userID int64) (CountRatingsRow, error) {
	row := q.db.QueryRowContext(ctx, countRatings, userID)
	var i CountRatingsRow
	err := row.Scan(&i.Liked, &i.Disliked, &i.Total)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteRating = `-- name: DeleteRating :exec
DELETE FROM ratings WHERE user_id = ? AND show_id = ?
`

type DeleteRatingParams struct {
	UserID int64
	ShowID string
}

func (q *Queries) DeleteRating(ctx context.Context, arg DeleteRatingParams) error {
	_, err := q.db.ExecContext(ctx, deleteRating, arg.UserID, arg.ShowID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getDislikedShows = `-- name: GetDislikedShows :many
SELECT s.id, s.tmdb_id, s.title, s.year, s.poster_path, s.genre, s.synopsis, s.popularity, s.cached_at FROM shows s
JOIN ratings r ON r.show_id = s.id AND r.user_id = ? AND r.rating = 'disliked'
ORDER BY r.rated_at DESC
`

func (q *Queries) GetDislikedShows(ctx context.Context, userID int64) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getDislikedShows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikedShows = `-- name: GetLikedShows :many
SELECT s.id, s.tmdb_id, s.title, s.year, s.poster_path, s.genre, s.synopsis, s.popularity, s.cached_at FROM shows s
JOIN ratings r ON r.show_id = s.id AND r.user_id = ? AND r.rating = 'liked'
ORDER BY r.rated_at DESC
`

func (q *Queries) GetLikedShows(ctx context.Context, userID int64) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getLikedShows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT token, user_id, expires_at FROM sessions WHERE token = ? AND expires_at > datetime('now')
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(&i.Token, &i.UserID, &i.ExpiresAt)
	return i, err
}

const getShowByID = `-- name: GetShowByID :one
SELECT id, tmdb_id, title, year, poster_path, genre, synopsis, popularity, cached_at FROM shows WHERE id = ?
`

func (q *Queries) GetShowByID(ctx context.Context, id string) (Show, error) {
	row := q.db.QueryRowContext(ctx, getShowByID, id)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.PosterPath,
		&i.Genre,
		&i.Synopsis,
		&i.Popularity,
		&i.CachedAt,
	)
	return i, err
}

const getShows = `-- name: GetShows :many
SELECT id, tmdb_id, title, year, poster_path, genre, synopsis, popularity, cached_at FROM shows ORDER BY popularity DESC
`

func (q *Queries) GetShows(ctx context.Context) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnratedShows = `-- name: GetUnratedShows :many
SELECT s.id, s.tmdb_id, s.title, s.year, s.poster_path, s.genre, s.synopsis, s.popularity, s.cached_at FROM shows s
LEFT JOIN ratings r ON r.show_id = s.id AND r.user_id = ?
WHERE r.show_id IS NULL
ORDER BY s.popularity DESC
`

func (q *Queries) GetUnratedShows(ctx context.Context, userID int64) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getUnratedShows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_sub, email, name, avatar_url, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRatings = `-- name: GetUserRatings :many
SELECT show_id, rating FROM ratings WHERE user_id = ?
`

type GetUserRatingsRow struct {
	ShowID string
	Rating string
}

func (q *Queries) GetUserRatings(ctx context.Context, userID int64) ([]GetUserRatingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRatingsRow
	for rows.Next() {
		var i GetUserRatingsRow
		if err := rows.Scan(&i.ShowID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRatingsWithShows = `-- name: GetUserRatingsWithShows :many
SELECT r.show_id, r.rating, s.title, s.poster_path, s.genre, s.year
FROM ratings r JOIN shows s ON s.id = r.show_id
WHERE r.user_id = ?
ORDER BY r.rated_at DESC
`

type GetUserRatingsWithShowsRow struct {
	ShowID     string
	Rating     string
	Title      string
	PosterPath sql.NullString
	Genre      sql.NullString
	Year       string
}

func (q *Queries) GetUserRatingsWithShows(ctx context.Context, userID int64) ([]GetUserRatingsWithShowsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRatingsWithShows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRatingsWithShowsRow
	for rows.Next() {
		var i GetUserRatingsWithShowsRow
		if err := rows.Scan(
			&i.ShowID,
			&i.Rating,
			&i.Title,
			&i.PosterPath,
			&i.Genre,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerdict = `-- name: GetVerdict :one
SELECT user_id, verdict, headline, show_id, created_at FROM verdicts WHERE user_id = ? AND created_at > datetime('now', '-1 day')
`

func (q *Queries) GetVerdict(ctx context.Context, userID int64) (Verdict, error) {
	row := q.db.QueryRowContext(ctx, getVerdict, userID)
	var i Verdict
	err := row.Scan(
		&i.UserID,
		&i.Verdict,
		&i.Headline,
		&i.ShowID,
		&i.CreatedAt,
	)
	return i, err
}

const setRating = `-- name: SetRating :exec
INSERT INTO ratings (user_id, show_id, rating)
VALUES (?, ?, ?)
ON CONFLICT(user_id, show_id) DO UPDATE SET rating = excluded.rating, rated_at = CURRENT_TIMESTAMP
`

type SetRatingParams struct {
	UserID int64
	ShowID string
	Rating string
}

func (q *Queries) SetRating(ctx context.Context, arg SetRatingParams) error {
	_, err := q.db.ExecContext(ctx, setRating, arg.UserID, arg.ShowID, arg.Rating)
	return err
}

const updateShowMeta = `-- name: UpdateShowMeta :exec
UPDATE shows SET poster_path = ?, synopsis = ?, tmdb_id = ?, popularity = ?, cached_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateShowMetaParams struct {
	PosterPath sql.NullString
	Synopsis   sql.NullString
	TmdbID     sql.NullInt64
	Popularity sql.NullFloat64
	ID         string
}

func (q *Queries) UpdateShowMeta(ctx context.Context, arg UpdateShowMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateShowMeta,
		arg.PosterPath,
		arg.Synopsis,
		arg.TmdbID,
		arg.Popularity,
		arg.ID,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (google_sub, email, name, avatar_url)
VALUES (?, ?, ?, ?)
ON CONFLICT(google_sub) DO UPDATE SET email=excluded.email, name=excluded.name, avatar_url=excluded.avatar_url
RETURNING id, google_sub, email, name, avatar_url, created_at
`

type UpsertUserParams struct {
	GoogleSub string
	Email     string
	Name      string
	AvatarUrl sql.NullString
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.GoogleSub,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVerdict = `-- name: UpsertVerdict :exec
INSERT INTO verdicts (user_id, verdict, headline, show_id)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET verdict=excluded.verdict, headline=excluded.headline, show_id=excluded.show_id, created_at=CURRENT_TIMESTAMP
`

type UpsertVerdictParams struct {
	UserID   int64
	Verdict  string
	Headline string
	ShowID   sql.NullString
}

func (q *Queries) UpsertVerdict(ctx context.Context, arg UpsertVerdictParams) error {
	_, err := q.db.ExecContext(ctx, upsertVerdict,
		arg.UserID,
		arg.Verdict,
		arg.Headline,
		arg.ShowID,
	)
	return err
}
