// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const activatePartnership = `-- name: ActivatePartnership :exec
UPDATE partnerships SET status = 'active', partner_id = ? WHERE id = ?
`

type ActivatePartnershipParams struct {
	PartnerID sql.NullInt64
	ID        int64
}

func (q *Queries) ActivatePartnership(ctx context.Context, arg ActivatePartnershipParams) error {
	_, err := q.db.ExecContext(ctx, activatePartnership, arg.PartnerID, arg.ID)
	return err
}

const countRatings = `-- name: CountRatings :one
SELECT
  SUM(CASE WHEN rating='favourite' THEN 1 ELSE 0 END) AS favourite,
  SUM(CASE WHEN rating='liked' THEN 1 ELSE 0 END) AS liked,
  SUM(CASE WHEN rating='disliked' THEN 1 ELSE 0 END) AS disliked,
  COUNT(*) AS total
FROM ratings WHERE user_id = ?
`

type CountRatingsRow struct {
	Favourite sql.NullFloat64
	Liked     sql.NullFloat64
	Disliked  sql.NullFloat64
	Total     int64
}

func (q *Queries) CountRatings(ctx context.Context, userID int64) (CountRatingsRow, error) {
	row := q.db.QueryRowContext(ctx, countRatings, userID)
	var i CountRatingsRow
	err := row.Scan(
		&i.Favourite,
		&i.Liked,
		&i.Disliked,
		&i.Total,
	)
	return i, err
}

const countShows = `-- name: CountShows :one
SELECT COUNT(*) FROM shows
`

func (q *Queries) CountShows(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countShows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPartnership = `-- name: CreatePartnership :one
INSERT INTO partnerships (user_id, partner_email, partner_id, status)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, partner_id, partner_email, status, created_at
`

type CreatePartnershipParams struct {
	UserID       int64
	PartnerEmail string
	PartnerID    sql.NullInt64
	Status       string
}

func (q *Queries) CreatePartnership(ctx context.Context, arg CreatePartnershipParams) (Partnership, error) {
	row := q.db.QueryRowContext(ctx, createPartnership,
		arg.UserID,
		arg.PartnerEmail,
		arg.PartnerID,
		arg.Status,
	)
	var i Partnership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PartnerID,
		&i.PartnerEmail,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deletePartnership = `-- name: DeletePartnership :exec
DELETE FROM partnerships WHERE id = ?
`

func (q *Queries) DeletePartnership(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePartnership, id)
	return err
}

const deleteRating = `-- name: DeleteRating :exec
DELETE FROM ratings WHERE user_id = ? AND show_id = ?
`

type DeleteRatingParams struct {
	UserID int64
	ShowID string
}

func (q *Queries) DeleteRating(ctx context.Context, arg DeleteRatingParams) error {
	_, err := q.db.ExecContext(ctx, deleteRating, arg.UserID, arg.ShowID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteVerdict = `-- name: DeleteVerdict :exec
DELETE FROM verdicts WHERE user_id = ?
`

func (q *Queries) DeleteVerdict(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteVerdict, userID)
	return err
}

const getActivePartnershipsAsOwner = `-- name: GetActivePartnershipsAsOwner :many
SELECT p.id, p.user_id, p.partner_id, p.partner_email, p.status, p.created_at,
       u.name AS partner_name, u.avatar_url AS partner_avatar
FROM partnerships p
LEFT JOIN users u ON u.id = p.partner_id
WHERE p.user_id = ? AND p.status = 'active'
`

type GetActivePartnershipsAsOwnerRow struct {
	ID            int64
	UserID        int64
	PartnerID     sql.NullInt64
	PartnerEmail  string
	Status        string
	CreatedAt     time.Time
	PartnerName   sql.NullString
	PartnerAvatar sql.NullString
}

func (q *Queries) GetActivePartnershipsAsOwner(ctx context.Context, userID int64) ([]GetActivePartnershipsAsOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, getActivePartnershipsAsOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePartnershipsAsOwnerRow
	for rows.Next() {
		var i GetActivePartnershipsAsOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PartnerID,
			&i.PartnerEmail,
			&i.Status,
			&i.CreatedAt,
			&i.PartnerName,
			&i.PartnerAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePartnershipsAsPartner = `-- name: GetActivePartnershipsAsPartner :many
SELECT p.id, p.user_id, p.partner_id, p.partner_email, p.status, p.created_at,
       u.name AS partner_name, u.avatar_url AS partner_avatar
FROM partnerships p
LEFT JOIN users u ON u.id = p.user_id
WHERE p.partner_id = ? AND p.status = 'active'
`

type GetActivePartnershipsAsPartnerRow struct {
	ID            int64
	UserID        int64
	PartnerID     sql.NullInt64
	PartnerEmail  string
	Status        string
	CreatedAt     time.Time
	PartnerName   sql.NullString
	PartnerAvatar sql.NullString
}

func (q *Queries) GetActivePartnershipsAsPartner(ctx context.Context, partnerID sql.NullInt64) ([]GetActivePartnershipsAsPartnerRow, error) {
	rows, err := q.db.QueryContext(ctx, getActivePartnershipsAsPartner, partnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePartnershipsAsPartnerRow
	for rows.Next() {
		var i GetActivePartnershipsAsPartnerRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PartnerID,
			&i.PartnerEmail,
			&i.Status,
			&i.CreatedAt,
			&i.PartnerName,
			&i.PartnerAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBothLikedShows = `-- name: GetBothLikedShows :many
SELECT s.id, s.tmdb_id, s.title, s.year, s.poster_path, s.genre, s.synopsis, s.popularity, s.cached_at FROM shows s
JOIN ratings r1 ON r1.show_id = s.id AND r1.user_id = ? AND r1.rating IN ('liked', 'favourite')
JOIN ratings r2 ON r2.show_id = s.id AND r2.user_id = ? AND r2.rating IN ('liked', 'favourite')
ORDER BY s.popularity DESC
`

type GetBothLikedShowsParams struct {
	UserID   int64
	UserID_2 int64
}

func (q *Queries) GetBothLikedShows(ctx context.Context, arg GetBothLikedShowsParams) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getBothLikedShows, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDislikedShows = `-- name: GetDislikedShows :many
SELECT s.id, s.tmdb_id, s.title, s.year, s.poster_path, s.genre, s.synopsis, s.popularity, s.cached_at FROM shows s
JOIN ratings r ON r.show_id = s.id AND r.user_id = ? AND r.rating = 'disliked'
ORDER BY r.rated_at DESC
`

func (q *Queries) GetDislikedShows(ctx context.Context, userID int64) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getDislikedShows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFavouriteShows = `-- name: GetFavouriteShows :many
SELECT s.id, s.tmdb_id, s.title, s.year, s.poster_path, s.genre, s.synopsis, s.popularity, s.cached_at FROM shows s
JOIN ratings r ON r.show_id = s.id AND r.user_id = ? AND r.rating = 'favourite'
ORDER BY r.rated_at DESC
`

func (q *Queries) GetFavouriteShows(ctx context.Context, userID int64) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getFavouriteShows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomingPartnerRequests = `-- name: GetIncomingPartnerRequests :many
SELECT p.id, p.user_id, p.partner_email, p.status, p.created_at,
       u.name AS requester_name, u.email AS requester_email
FROM partnerships p
JOIN users u ON u.id = p.user_id
WHERE p.partner_email = ? AND p.status = 'pending'
`

type GetIncomingPartnerRequestsRow struct {
	ID             int64
	UserID         int64
	PartnerEmail   string
	Status         string
	CreatedAt      time.Time
	RequesterName  string
	RequesterEmail string
}

func (q *Queries) GetIncomingPartnerRequests(ctx context.Context, partnerEmail string) ([]GetIncomingPartnerRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIncomingPartnerRequests, partnerEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIncomingPartnerRequestsRow
	for rows.Next() {
		var i GetIncomingPartnerRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PartnerEmail,
			&i.Status,
			&i.CreatedAt,
			&i.RequesterName,
			&i.RequesterEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikedShows = `-- name: GetLikedShows :many
SELECT s.id, s.tmdb_id, s.title, s.year, s.poster_path, s.genre, s.synopsis, s.popularity, s.cached_at FROM shows s
JOIN ratings r ON r.show_id = s.id AND r.user_id = ? AND r.rating IN ('liked', 'favourite')
ORDER BY CASE WHEN r.rating = 'favourite' THEN 0 ELSE 1 END, r.rated_at DESC
`

func (q *Queries) GetLikedShows(ctx context.Context, userID int64) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getLikedShows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartnerVerdict = `-- name: GetPartnerVerdict :one
SELECT partnership_id, verdict, headline, show_id, created_at FROM partner_verdicts
WHERE partnership_id = ? AND created_at > datetime('now', '-1 day')
`

func (q *Queries) GetPartnerVerdict(ctx context.Context, partnershipID int64) (PartnerVerdict, error) {
	row := q.db.QueryRowContext(ctx, getPartnerVerdict, partnershipID)
	var i PartnerVerdict
	err := row.Scan(
		&i.PartnershipID,
		&i.Verdict,
		&i.Headline,
		&i.ShowID,
		&i.CreatedAt,
	)
	return i, err
}

const getPartnershipByID = `-- name: GetPartnershipByID :one
SELECT id, user_id, partner_id, partner_email, status, created_at FROM partnerships WHERE id = ?
`

func (q *Queries) GetPartnershipByID(ctx context.Context, id int64) (Partnership, error) {
	row := q.db.QueryRowContext(ctx, getPartnershipByID, id)
	var i Partnership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PartnerID,
		&i.PartnerEmail,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingPartnershipsByUser = `-- name: GetPendingPartnershipsByUser :many
SELECT id, user_id, partner_id, partner_email, status, created_at FROM partnerships
WHERE user_id = ? AND status = 'pending'
`

func (q *Queries) GetPendingPartnershipsByUser(ctx context.Context, userID int64) ([]Partnership, error) {
	rows, err := q.db.QueryContext(ctx, getPendingPartnershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partnership
	for rows.Next() {
		var i Partnership
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PartnerID,
			&i.PartnerEmail,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT token, user_id, expires_at FROM sessions WHERE token = ? AND expires_at > datetime('now')
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(&i.Token, &i.UserID, &i.ExpiresAt)
	return i, err
}

const getShowByID = `-- name: GetShowByID :one
SELECT id, tmdb_id, title, year, poster_path, genre, synopsis, popularity, cached_at FROM shows WHERE id = ?
`

func (q *Queries) GetShowByID(ctx context.Context, id string) (Show, error) {
	row := q.db.QueryRowContext(ctx, getShowByID, id)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.PosterPath,
		&i.Genre,
		&i.Synopsis,
		&i.Popularity,
		&i.CachedAt,
	)
	return i, err
}

const getShowByTitle = `-- name: GetShowByTitle :one
SELECT id, tmdb_id, title, year, poster_path, genre, synopsis, popularity, cached_at FROM shows WHERE LOWER(title) = LOWER(?) LIMIT 1
`

func (q *Queries) GetShowByTitle(ctx context.Context, lower string) (Show, error) {
	row := q.db.QueryRowContext(ctx, getShowByTitle, lower)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.PosterPath,
		&i.Genre,
		&i.Synopsis,
		&i.Popularity,
		&i.CachedAt,
	)
	return i, err
}

const getShowByTmdbID = `-- name: GetShowByTmdbID :one
SELECT id, tmdb_id, title, year, poster_path, genre, synopsis, popularity, cached_at FROM shows WHERE tmdb_id = ?
`

func (q *Queries) GetShowByTmdbID(ctx context.Context, tmdbID sql.NullInt64) (Show, error) {
	row := q.db.QueryRowContext(ctx, getShowByTmdbID, tmdbID)
	var i Show
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.PosterPath,
		&i.Genre,
		&i.Synopsis,
		&i.Popularity,
		&i.CachedAt,
	)
	return i, err
}

const getShows = `-- name: GetShows :many
SELECT id, tmdb_id, title, year, poster_path, genre, synopsis, popularity, cached_at FROM shows ORDER BY popularity DESC
`

func (q *Queries) GetShows(ctx context.Context) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopShows = `-- name: GetTopShows :many
SELECT id, tmdb_id, title, year, poster_path, genre, synopsis, popularity, cached_at FROM shows ORDER BY popularity DESC LIMIT ?
`

func (q *Queries) GetTopShows(ctx context.Context, limit int64) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getTopShows, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnratedShows = `-- name: GetUnratedShows :many
SELECT s.id, s.tmdb_id, s.title, s.year, s.poster_path, s.genre, s.synopsis, s.popularity, s.cached_at FROM shows s
LEFT JOIN ratings r ON r.show_id = s.id AND r.user_id = ?
WHERE r.show_id IS NULL
ORDER BY s.popularity DESC
`

func (q *Queries) GetUnratedShows(ctx context.Context, userID int64) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, getUnratedShows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.PosterPath,
			&i.Genre,
			&i.Synopsis,
			&i.Popularity,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, google_sub, email, name, avatar_url, created_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_sub, email, name, avatar_url, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRatings = `-- name: GetUserRatings :many
SELECT show_id, rating FROM ratings WHERE user_id = ?
`

type GetUserRatingsRow struct {
	ShowID string
	Rating string
}

func (q *Queries) GetUserRatings(ctx context.Context, userID int64) ([]GetUserRatingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRatingsRow
	for rows.Next() {
		var i GetUserRatingsRow
		if err := rows.Scan(&i.ShowID, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRatingsWithShows = `-- name: GetUserRatingsWithShows :many
SELECT r.show_id, r.rating, s.title, s.poster_path, s.genre, s.year
FROM ratings r JOIN shows s ON s.id = r.show_id
WHERE r.user_id = ?
ORDER BY r.rated_at DESC
`

type GetUserRatingsWithShowsRow struct {
	ShowID     string
	Rating     string
	Title      string
	PosterPath sql.NullString
	Genre      sql.NullString
	Year       string
}

func (q *Queries) GetUserRatingsWithShows(ctx context.Context, userID int64) ([]GetUserRatingsWithShowsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRatingsWithShows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRatingsWithShowsRow
	for rows.Next() {
		var i GetUserRatingsWithShowsRow
		if err := rows.Scan(
			&i.ShowID,
			&i.Rating,
			&i.Title,
			&i.PosterPath,
			&i.Genre,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerdict = `-- name: GetVerdict :one
SELECT user_id, verdict, headline, show_id, created_at FROM verdicts WHERE user_id = ? AND created_at > datetime('now', '-1 day')
`

func (q *Queries) GetVerdict(ctx context.Context, userID int64) (Verdict, error) {
	row := q.db.QueryRowContext(ctx, getVerdict, userID)
	var i Verdict
	err := row.Scan(
		&i.UserID,
		&i.Verdict,
		&i.Headline,
		&i.ShowID,
		&i.CreatedAt,
	)
	return i, err
}

const insertShow = `-- name: InsertShow :exec
INSERT OR IGNORE INTO shows (id, tmdb_id, title, year, poster_path, genre, synopsis, popularity)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertShowParams struct {
	ID         string
	TmdbID     sql.NullInt64
	Title      string
	Year       string
	PosterPath sql.NullString
	Genre      sql.NullString
	Synopsis   sql.NullString
	Popularity sql.NullFloat64
}

func (q *Queries) InsertShow(ctx context.Context, arg InsertShowParams) error {
	_, err := q.db.ExecContext(ctx, insertShow,
		arg.ID,
		arg.TmdbID,
		arg.Title,
		arg.Year,
		arg.PosterPath,
		arg.Genre,
		arg.Synopsis,
		arg.Popularity,
	)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.name, u.avatar_url, u.created_at,
       COUNT(r.show_id) AS rating_count
FROM users u
LEFT JOIN ratings r ON r.user_id = u.id
GROUP BY u.id
ORDER BY u.created_at DESC
`

type ListUsersRow struct {
	ID          int64
	Email       string
	Name        string
	AvatarUrl   sql.NullString
	CreatedAt   time.Time
	RatingCount int64
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.RatingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRating = `-- name: SetRating :exec
INSERT INTO ratings (user_id, show_id, rating)
VALUES (?, ?, ?)
ON CONFLICT(user_id, show_id) DO UPDATE SET rating = excluded.rating, rated_at = CURRENT_TIMESTAMP
`

type SetRatingParams struct {
	UserID int64
	ShowID string
	Rating string
}

func (q *Queries) SetRating(ctx context.Context, arg SetRatingParams) error {
	_, err := q.db.ExecContext(ctx, setRating, arg.UserID, arg.ShowID, arg.Rating)
	return err
}

const updateShowMeta = `-- name: UpdateShowMeta :exec
UPDATE shows SET poster_path = ?, synopsis = ?, tmdb_id = ?, popularity = ?, cached_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateShowMetaParams struct {
	PosterPath sql.NullString
	Synopsis   sql.NullString
	TmdbID     sql.NullInt64
	Popularity sql.NullFloat64
	ID         string
}

func (q *Queries) UpdateShowMeta(ctx context.Context, arg UpdateShowMetaParams) error {
	_, err := q.db.ExecContext(ctx, updateShowMeta,
		arg.PosterPath,
		arg.Synopsis,
		arg.TmdbID,
		arg.Popularity,
		arg.ID,
	)
	return err
}

const upsertPartnerVerdict = `-- name: UpsertPartnerVerdict :exec
INSERT INTO partner_verdicts (partnership_id, verdict, headline, show_id)
VALUES (?, ?, ?, ?)
ON CONFLICT(partnership_id) DO UPDATE SET
  verdict=excluded.verdict, headline=excluded.headline,
  show_id=excluded.show_id, created_at=CURRENT_TIMESTAMP
`

type UpsertPartnerVerdictParams struct {
	PartnershipID int64
	Verdict       string
	Headline      string
	ShowID        sql.NullString
}

func (q *Queries) UpsertPartnerVerdict(ctx context.Context, arg UpsertPartnerVerdictParams) error {
	_, err := q.db.ExecContext(ctx, upsertPartnerVerdict,
		arg.PartnershipID,
		arg.Verdict,
		arg.Headline,
		arg.ShowID,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (google_sub, email, name, avatar_url)
VALUES (?, ?, ?, ?)
ON CONFLICT(google_sub) DO UPDATE SET email=excluded.email, name=excluded.name, avatar_url=excluded.avatar_url
RETURNING id, google_sub, email, name, avatar_url, created_at
`

type UpsertUserParams struct {
	GoogleSub string
	Email     string
	Name      string
	AvatarUrl sql.NullString
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.GoogleSub,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVerdict = `-- name: UpsertVerdict :exec
INSERT INTO verdicts (user_id, verdict, headline, show_id)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET verdict=excluded.verdict, headline=excluded.headline, show_id=excluded.show_id, created_at=CURRENT_TIMESTAMP
`

type UpsertVerdictParams struct {
	UserID   int64
	Verdict  string
	Headline string
	ShowID   sql.NullString
}

func (q *Queries) UpsertVerdict(ctx context.Context, arg UpsertVerdictParams) error {
	_, err := q.db.ExecContext(ctx, upsertVerdict,
		arg.UserID,
		arg.Verdict,
		arg.Headline,
		arg.ShowID,
	)
	return err
}
